baseURL = 'https://pixelpromenade.eu/'
languageCode = 'fr'
title = 'Pixel Promenade'
theme = 'dream'

[params]
  lightTheme = "emerald"
  darkTheme = "forest"

  author = "Kaz"
  description = "Un blog expérimental."
  avatar = "img/personal/avatar.jpg"
  

  defaultTheme = "light"

  headerTitle = "Pixel Promenade"
  motto = "Du café, des livres et une clarinette"


  footerBottomText = "Un blog expérimental."


[[menu.main]]
  identifier = "about"
  name = "À Propos"
  url = "/about/"

[[menu.main]]
  identifier = "posts"
  name = "Articles"
  url = "/posts/"